# build
FROM node:16-alpine AS builder

WORKDIR /product-service

COPY package*.json ./
RUN npm install
COPY . .

# Production/dev
FROM node:16-alpine

WORKDIR /product-service

COPY --from=builder /product-service .

EXPOSE 3000

CMD ["npm", "start"]