services:
  proxy:
    build:
      context: .
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - frontend
      - auth-service
      - product-service
      - order-service
    networks:
      - e-commerce-network

  frontend:
    build:
      #   context: ./frontend
      target: prod
    env_file: ./frontend/.env.production
    ports:
      - 8000:8000

  auth-service:
    build:
      #   context: ./services/auth-service
      target: prod
    env_file: ./services/auth-service/.env.production

  product-service:
    build:
      #   context: ./services/product-service
      target: prod
    env_file: ./services/product-service/.env.production

  order-service:
    build:
      #   context: ./services/order-service
      target: prod
    env_file: ./services/order-service/.env.production

  init-products:
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile-init-products
    env_file: ./.env.production
