FROM alpine:latest

WORKDIR init-products/

RUN addgroup -g 1504 init-group && adduser -D -u 1504 -G init-group init-user

COPY ./scripts/init-products.sh ./init-products.sh

RUN sed -i 's/\r$//' ./init-products.sh

RUN apk add --no-cache bash curl

RUN chown -R init-user:init-group /init-products

USER init-user

CMD ["bash", "init-products.sh"]
