services:
  frontend:
    build:
      context: ./frontend
    env_file: ./frontend/.env.dev
    ports:
      - 8080:8080
  auth-service:
    container_name: auth-service
    build:
      context: ./services/auth-service
    env_file: ./services/auth-service/.env.dev
    ports:
      - 3001:3001
  product-service:
    container_name: product-service
    build:
      context: ./services/product-service
    env_file: ./services/product-service/.env.dev
    ports:
      - 3000:3000
  order-service:
    container_name: order-service
    build:
      context: ./services/order-service
    env_file: ./services/order-service/.env.dev
    ports:
      - 3002:3002
  database:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017